on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test gifos
    steps:
      - uses: actions/checkout@v4
      - name: check
        run: |
          ls
          whoami
          pwd
